from aiogram import Bot, Dispatcher, executor, types
from config import TOKEN
import keyboard as kb
from aiogram.types import CallbackQuery

bot = Bot(token=TOKEN)
dp = Dispatcher(bot)


@dp.message_handler(commands=['start'])
async def start(message: types.Message):
    await bot.send_message(message.chat.id, "Привет,выбери предмет который тебе нужен", reply_markup=kb.button)


@dp.callback_query_handler(lambda call: True)
async def keyboard_all(call: CallbackQuery):
    # Биология это все
    if call.data == 'biology':
        photo = open('photo/1.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, photo)
        await bot.send_message(call.message.chat.id, '1-я страничка', reply_markup=kb.bt)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'back':
        await bot.send_message(call.message.chat.id, "Вы в главном меню", reply_markup=kb.button)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'knost':
        img = open('photo/2.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, img)
        await bot.send_message(call.message.chat.id, "2-я страничка", reply_markup=kb.bg)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'lorst':
        ig = open('photo/1.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, ig)
        await bot.send_message(call.message.chat.id, "Вы вернулись обратно", reply_markup=kb.bt)
    elif call.data == 'back_2':
        await bot.send_message(call.message.chat.id, "Вы в главном меню", reply_markup=kb.button)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'konsp_3':
        i = open('photo/3.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, i)
        await bot.send_message(call.message.chat.id, "3-я страничка", reply_markup=kb.vb)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'fg':
        ig = open('photo/2.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, ig)
        await bot.send_message(call.message.chat.id, "Вы вернулись обратно", reply_markup=kb.bg)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'back_3':
        await bot.send_message(call.message.chat.id, "Вы в главном меню", reply_markup=kb.button)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'fg_2':
        ip = open('photo/4.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, ip)
        await bot.send_message(call.message.chat.id, "4-я страничка", reply_markup=kb.vd)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'back_4':
        await bot.send_message(call.message.chat.id, "Вы в главном меню", reply_markup=kb.button)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'fg_3':
        ld = open('photo/3.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, ld)
        await bot.send_message(call.message.chat.id, "Вы вернулись обратно", reply_markup=kb.vb)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)

    elif call.data == 'fg_4':
        lb = open('photo/5.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, lb)
        await bot.send_message(call.message.chat.id, "5-я страничка", reply_markup=kb.vg)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'back_5':
        await bot.send_message(call.message.chat.id, "Вы в главном меню", reply_markup=kb.button)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)

    elif call.data == 'fg_5':
        lh = open('photo/4.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, lh)
        await bot.send_message(call.message.chat.id, "Вы вернулись обратно", reply_markup=kb.vd)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'fg_6':
        lj = open('photo/6.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, lj)
        await bot.send_message(call.message.chat.id, "6-я страница", reply_markup=kb.vh)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'back_6':
        await bot.send_message(call.message.chat.id, "Вы в главном меню", reply_markup=kb.button)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'fg_7':
        lh = open('photo/5.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, lh)
        await bot.send_message(call.message.chat.id, "Вы вернулись обратно", reply_markup=kb.vg)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'fg_8':
        lly = open('photo/7.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, lly)
        await bot.send_message(call.message.chat.id, "7-я страничка", reply_markup=kb.vl)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'fg_9':
        lhj = open('photo/6.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, lhj)
        await bot.send_message(call.message.chat.id, "Вы вернулись обратно", reply_markup=kb.vh)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'back_7':
        await bot.send_message(call.message.chat.id, "Вы в главном меню", reply_markup=kb.button)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'fg_10':
        lhz = open('photo/8.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, lhz)
        await bot.send_message(call.message.chat.id, "8-страничка", reply_markup=kb.vk)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'back_8':
        await bot.send_message(call.message.chat.id, "Вы в главном меню", reply_markup=kb.button)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'fg_11':
        ldg = open('photo/7.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, ldg)
        await bot.send_message(call.message.chat.id, "Вы вернулись обратно", reply_markup=kb.vl)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'fg_12':
        ddh = open('photo/9.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, ddh)
        await bot.send_message(call.message.chat.id, "9-я страничка", reply_markup=kb.vkl)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'back_9':
        await bot.send_message(call.message.chat.id, "Вы в главном меню", reply_markup=kb.button)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'fg_13':
        cdh = open('photo/8.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, cdh)
        await bot.send_message(call.message.chat.id, "Вы вернулись обратно", reply_markup=kb.vk)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'fg_14':
        lds = open('photo/10.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, lds)
        await bot.send_message(call.message.chat.id, "10-я страничка", reply_markup=kb.vgl)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'back_10':
        await bot.send_message(call.message.chat.id, "Вы в главном меню", reply_markup=kb.button)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'fg_15':
        ldh = open('photo/9.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, ldh)
        await bot.send_message(call.message.chat.id, "Вы вернулись обратно", reply_markup=kb.vkl)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'fg_16':
        lds = open('photo/11.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, lds)
        await bot.send_message(call.message.chat.id, "11-я страничка", reply_markup=kb.sgl)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'back_11':
        await bot.send_message(call.message.chat.id, "Вы в главном меню", reply_markup=kb.button)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'fg_17':
        ldhs = open('photo/10.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, ldhs)
        await bot.send_message(call.message.chat.id, "Вы вернулись обратно", reply_markup=kb.vgl)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'fg_18':
        ldhs = open('photo/12.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, ldhs)
        await bot.send_message(call.message.chat.id, "12-я страничка", reply_markup=kb.sgs)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'back_12':
        await bot.send_message(call.message.chat.id, "Вы в главном меню", reply_markup=kb.button)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'fg_19':
        ldvs = open('photo/11.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, ldvs)
        await bot.send_message(call.message.chat.id, "Вы вернулись обратно", reply_markup=kb.sgl)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'fg_20':
        zd = open('photo/13.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, zd)
        await bot.send_message(call.message.chat.id, "13-я страничка", reply_markup=kb.sds)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'back_13':
        await bot.send_message(call.message.chat.id, "Вы в главном меню", reply_markup=kb.button)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'fg_21':
        ad = open('photo/12.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, ad)
        await bot.send_message(call.message.chat.id, "Вы вернулись обратно", reply_markup=kb.sgs)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'fg_22':
        gd = open('photo/14.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, gd)
        await bot.send_message(call.message.chat.id, "14-я страничка", reply_markup=kb.sdz)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'back_14':
        await bot.send_message(call.message.chat.id, "Вы в главном меню", reply_markup=kb.button)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'fg_23':
        gh = open('photo/13.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, gh)
        await bot.send_message(call.message.chat.id, "Вы вернулись обратно", reply_markup=kb.sds)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'fg_24':
        ghd = open('photo/15.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, ghd)
        await bot.send_message(call.message.chat.id, "15-я страничка", reply_markup=kb.adz)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'back_15':
        await bot.send_message(call.message.chat.id, "Вы в главном меню", reply_markup=kb.button)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'fg_25':
        gh_1 = open('photo/14.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, gh_1)
        await bot.send_message(call.message.chat.id, "Вы вернулись обратно", reply_markup=kb.sdz)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'fg_25':
        gh_2 = open('photo/14.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, gh_2)
        await bot.send_message(call.message.chat.id, "Вы вернулись обратно", reply_markup=kb.sdz)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'back_16':
        await bot.send_message(call.message.chat.id, "Вы в главном меню", reply_markup=kb.button)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'fg_26':
        gh_3 = open('photo/16.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, gh_3)
        await bot.send_message(call.message.chat.id, "16-я страничка", reply_markup=kb.bdz)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'fg_27':
        gh_4 = open('photo/15.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, gh_4)
        await bot.send_message(call.message.chat.id, "17-я страница", reply_markup=kb.adz)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'back_17':
        await bot.send_message(call.message.chat.id, "Вы в главном меню", reply_markup=kb.button)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'fg_28':
        gh_5 = open('photo/17.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, gh_5)
        await bot.send_message(call.message.chat.id, "17-я страничка", reply_markup=kb.cdz)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'back_18':
        await bot.send_message(call.message.chat.id, "Вы в главном меню", reply_markup=kb.button)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'fg_29':
        gh_6 = open('photo/16.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, gh_6)
        await bot.send_message(call.message.chat.id, "Вы вернулись обратно", reply_markup=kb.bdz)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'fg_30':
        gh_6 = open('photo/18.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, gh_6)
        await bot.send_message(call.message.chat.id, "18-я страничка", reply_markup=kb.mdz)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'back_19':
        await bot.send_message(call.message.chat.id, "Вы в главном меню", reply_markup=kb.button)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'fg_31':
        gh_7 = open('photo/17.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, gh_7)
        await bot.send_message(call.message.chat.id, "Вы вернулись обратно", reply_markup=kb.cdz)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'fg_32':
        gh_8 = open('photo/19.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, gh_8)
        await bot.send_message(call.message.chat.id, "19-я страничка", reply_markup=kb.cmz)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'back_20':
        await bot.send_message(call.message.chat.id, "Вы в главном меню", reply_markup=kb.button)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'fg_33':
        gh_9 = open('photo/18.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, gh_9)
        await bot.send_message(call.message.chat.id, "Вы вернулись обратно", reply_markup=kb.mdz)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'fg_34':
        gh_10 = open('photo/20.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, gh_10)
        await bot.send_message(call.message.chat.id, "20-я страничка", reply_markup=kb.zdz)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'back_20':
        await bot.send_message(call.message.chat.id, "Вы в главном меню", reply_markup=kb.button)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'fg_35':
        gh_11 = open('photo/19.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, gh_11)
        await bot.send_message(call.message.chat.id, "Вы вернулись обратно", reply_markup=kb.cmz)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'fg_36':
        gh_11 = open('photo/21.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, gh_11)
        await bot.send_message(call.message.chat.id, "21-я страничка", reply_markup=kb.ydz)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'back_21':
        await bot.send_message(call.message.chat.id, "Вы в главном меню", reply_markup=kb.button)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'fg_37':
        gh_12 = open('photo/20.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, gh_12)
        await bot.send_message(call.message.chat.id, "Вы вернулись обратно", reply_markup=kb.zdz)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'fg_38':
        gh_13 = open('photo/22.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, gh_13)
        await bot.send_message(call.message.chat.id, "22-я страничка", reply_markup=kb.gdz)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'back_22':
        await bot.send_message(call.message.chat.id, "Вы в главном меню", reply_markup=kb.button)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'fg_39':
        gh_14 = open('photo/21.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, gh_14)
        await bot.send_message(call.message.chat.id, "Вы вернулись обратно", reply_markup=kb.ydz)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
# География
    elif call.data == 'geography':
        ph = open('photo/География/1.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, ph)
        await bot.send_message(call.message.chat.id, '1-я страничка', reply_markup=kb.geo)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
    elif call.data == 'main':
        await bot.send_message(call.message.chat.id, "Вы в главном меню", reply_markup=kb.button)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'photo':
        ph_2 = open('photo/География/2.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, ph_2)
        await bot.send_message(call.message.chat.id, "2-я страница", reply_markup=kb.geo_1)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'main_2':
        await bot.send_message(call.message.chat.id, "Вы в главном меню", reply_markup=kb.button)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'laf':
        ph = open('photo/География/1.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, ph)
        await bot.send_message(call.message.chat.id, "Вы вернулись на прошлую страницу", reply_markup=kb.geo)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'photo_2':
        ph_3 = open('photo/География/3.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, ph_3)
        await bot.send_message(call.message.chat.id, "3-я страница", reply_markup=kb.geo_2)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'main_3':
        await bot.send_message(call.message.chat.id, "Вы в главном меню", reply_markup=kb.button)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'laf_2':
        ph_2 = open('photo/География/2.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, ph_2)
        await bot.send_message(call.message.chat.id, "Вы вернулись на прошлую страницу", reply_markup=kb.geo_1)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'photo_3':
        ph_4 = open('photo/География/4.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, ph_4)
        await bot.send_message(call.message.chat.id, "4-я страница", reply_markup=kb.geo_3)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'main_4':
        await bot.send_message(call.message.chat.id, "Вы в главном меню", reply_markup=kb.button)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'laf_3':
        ph_5 = open('photo/География/3.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, ph_5)
        await bot.send_message(call.message.chat.id, "Вы вернулись на прошлую страницу", reply_markup=kb.geo_2)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'photo_4':
        ph_6 = open('photo/География/5.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, ph_6)
        await bot.send_message(call.message.chat.id, "5-я страница", reply_markup=kb.gh_3)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'main_5':
        await bot.send_message(call.message.chat.id, "Вы в главном меню", reply_markup=kb.button)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'laf_4':
        ph_5 = open('photo/География/4.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, ph_5)
        await bot.send_message(call.message.chat.id, "Вы вернулись на прошлую страницу", reply_markup=kb.geo_3)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'photo_5':
        ph_7 = open('photo/География/6.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, ph_7)
        await bot.send_message(call.message.chat.id, "6-я страница", reply_markup=kb.gl_3)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'main_6':
        await bot.send_message(call.message.chat.id, "Вы в главном меню", reply_markup=kb.button)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'laf_5':
        ph_8 = open('photo/География/5.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, ph_8)
        await bot.send_message(call.message.chat.id, "Вы вернулись на прошлую страницу", reply_markup=kb.gh_3)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'photo_6':
        ph_10 = open('photo/География/7.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, ph_10)
        await bot.send_message(call.message.chat.id, "7-я страница", reply_markup=kb.gd)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'main_7':
        await bot.send_message(call.message.chat.id, "Вы в главном меню", reply_markup=kb.button)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'laf_6':
        ph_8 = open('photo/География/6.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, ph_8)
        await bot.send_message(call.message.chat.id, "Вы вернулись на прошлую страницу", reply_markup=kb.gl_3)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'photo_7':
        ph_11 = open('photo/География/8.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, ph_11)
        await bot.send_message(call.message.chat.id, "8-я страница", reply_markup=kb.gb)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'main_8':
        await bot.send_message(call.message.chat.id, "Вы в главном меню", reply_markup=kb.button)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'laf_7':
        ph_22 = open('photo/География/7.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, ph_22)
        await bot.send_message(call.message.chat.id, "Вы вернулись на прошлую страницу", reply_markup=kb.gd)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'photo_8':
        ph_11 = open('photo/География/9.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, ph_11)
        await bot.send_message(call.message.chat.id, "9-я страница", reply_markup=kb.gbd)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'main_9':
        await bot.send_message(call.message.chat.id, "Вы в главном меню", reply_markup=kb.button)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'laf_8':
        ph_22 = open('photo/География/8.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, ph_22)
        await bot.send_message(call.message.chat.id, "Вы вернулись на прошлую страницу", reply_markup=kb.gb)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'photo_9':
        ph_12 = open('photo/География/10.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, ph_12)
        await bot.send_message(call.message.chat.id, "10-я страница", reply_markup=kb.gld)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'main_10':
        await bot.send_message(call.message.chat.id, "Вы в главном меню", reply_markup=kb.button)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'laf_9':
        ph_23 = open('photo/География/9.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, ph_23)
        await bot.send_message(call.message.chat.id, "Вы вернулись на прошлую страницу", reply_markup=kb.gbd)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'photo_10':
        await bot.send_message(call.message.chat.id, "Временно недоступно пропишите /start чтобы вернуться в главное меню")
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
    # Английский
    elif call.data == 'english':
        await bot.send_message(call.message.chat.id, "Выберите,что вам нужно", reply_markup=kb.eng_main)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
    elif call.data == 'words':
        word = open('photo/Английский/Словарь/1.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, word)
        await bot.send_message(call.message.chat.id, "1-я страница", reply_markup=kb.word)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'main_menu':
        await bot.send_message(call.message.chat.id, "Вы в главном меню", reply_markup=kb.button)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == '2_search':
        lgbr = open('photo/Английский/Словарь/2.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, lgbr)
        await bot.send_message(call.message.chat.id, "2-я страница" , reply_markup=kb.wtfg)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
    elif call.data == 'main_menu_2':
        await bot.send_message(call.message.chat.id, "Вы в главном меню", reply_markup=kb.button)
        await bot.edit_message_reply_markup(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
    elif call.data == 'return':
        word = open('photo/Английский/Словарь/1.jpg', 'rb')
        await bot.send_photo(call.message.chat.id, word)
        await bot.send_message(call.message.chat.id, "Вы вернулись обратно", reply_markup=kb.word)
        await bot.delete_message(call.message.chat.id, call.message.message_id)
        await bot.delete_message(call.message.chat.id, call.message.message_id - 1)
if __name__ == "__main__":
    executor.start_polling(dp, skip_updates=True)
